// Explicit column lists for each table, excluding the three embedding columns
// (embedding, embedding_updated_at, embedding_model_version).
//
// The embedding column is vector(1024) — ~8-12KB of JSON floats per row when
// transferred over the wire. Using these constants instead of select('*') saves
// ~250KB per candidates-list page view and ~750KB per smart-search hydration.
//
// Code that needs the embedding column (e.g. find_similar_candidates) must
// select it explicitly and should NOT use these constants.
//
// search_vector is included — it's small (tsvector) and harmless to fetch.

export const CANDIDATE_COLUMNS = [
  'id',
  'first_name',
  'last_name',
  'email',
  'email_secondary',
  'phone',
  'linkedin_url',
  'location_city',
  'location_state',
  'location_country',
  'current_title',
  'current_company',
  'category',
  'seniority_level',
  'manages_people',
  'years_experience',
  'skills',
  'headline',
  'certifications',
  'education_summary',
  'current_compensation',
  'desired_compensation',
  'willing_to_relocate',
  'relocation_preferences',
  'status',
  'source',
  'referred_by_type',
  'referred_by_id',
  'referred_by_text',
  'linked_contact_id',
  'last_contacted_at',
  'is_star',
  'created_at',
  'updated_at',
  'created_by',
  'search_vector',
].join(', ') as '*'

export const COMPANY_COLUMNS = [
  'id',
  'name',
  'domain',
  'company_type',
  'industry',
  'hq_city',
  'hq_state',
  'hq_country',
  'website_url',
  'linkedin_url',
  'status',
  'prospect_stage',
  'prospect_stage_entered_at',
  'priority',
  'why_target',
  'source',
  'next_step',
  'next_step_due_date',
  'disposition',
  'fee_agreement_pct',
  'became_client_at',
  'last_contacted_at',
  'what_they_do',
  'target_customer_profile',
  'company_size',
  'key_products_services',
  'target_buyer',
  'growth_stage',
  'hiring_signal',
  'referred_by_type',
  'referred_by_id',
  'referred_by_text',
  'created_at',
  'updated_at',
  'created_by',
  'search_vector',
].join(', ') as '*'

export const CONTACT_COLUMNS = [
  'id',
  'company_id',
  'first_name',
  'last_name',
  'title',
  'email',
  'email_secondary',
  'phone',
  'linkedin_url',
  'contact_type',
  'is_primary',
  'manages_people',
  'reports_to_id',
  'linked_candidate_id',
  'influence_level',
  'last_contacted_at',
  'created_at',
  'updated_at',
  'created_by',
  'search_vector',
].join(', ') as '*'

export const NOTE_COLUMNS = [
  'id',
  'entity_type',
  'entity_id',
  'content',
  'note_type',
  'linked_job_id',
  'is_private',
  'created_by',
  'created_at',
  'updated_at',
  'search_vector',
].join(', ') as '*'

export const JOB_OPENING_COLUMNS = [
  'id',
  'company_id',
  'hiring_manager_id',
  'title',
  'category',
  'seniority_level',
  'description',
  'requirements',
  'location_city',
  'location_state',
  'location_type',
  'comp_range_low',
  'comp_range_high',
  'status',
  'priority',
  'source',
  'next_step',
  'next_step_due_date',
  'travel_percentage',
  'fee_percentage_override',
  'opened_at',
  'filled_at',
  'closed_at',
  'created_at',
  'updated_at',
  'created_by',
  'search_vector',
].join(', ') as '*'
